Latvian: add multiple missing translations
svenfuchs/rails-i18n pull request #966
Opened 2022-01-04 09:56 UTC by MartinsLapsa

Includes validation messages, storage units, and other.

2022-06-08 23:40 UTC, pama requested changes

2022-06-08 23:40 UTC, pama commented on rails/locale/lv.yml
> +      x_years:
x_years key seems inexistent from the Action View locale:

https://github.com/rails/rails/blob/f95c0b7e96eb36bc3efc0c5beffbb9e84ea664e4/actionview/lib/action_view/locale/en.yml)

2022-08-31 11:09 UTC, pama requested changes

2022-09-08 19:15 UTC, digitalfrost commented on rails/locale/lv.yml
> +        one: 1 gads
```suggestion
```

2022-09-08 19:15 UTC, digitalfrost commented on rails/locale/lv.yml
> +        other: "%{count} gadi"
```suggestion
```

2022-09-08 19:15 UTC, digitalfrost commented on rails/locale/lv.yml
> +      x_years:
```suggestion
```

2022-09-08 19:21 UTC, digitalfrost commented
@pama -  this should fix the changes you requested.

2022-09-08 21:55 UTC, pama commented
@digitalfrost thank you!

2022-09-08 21:55 UTC, merged